# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acb318d85910624fbfaaf773fec7ea8445f65929e9fdf9d4035018d3a427d14df2a0aa48ba546af98c6b2e6249ba1e601e61f0bb1221103e79851afd244d2a52

test:
  secret_key_base: dcc28f46013810e57e6346a62d5113d289cbf36c6d787ec1e5d03f5c1ade8e14cb528af0c150fcb5f96e9dff07d4a86edf7bb0809e7d8bf19778376547d4e006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
